project:
  type: book

book:
  title: "ADRF User Guide"
  author: "Jon Mills, Josh Edelmann, and Corey Sparks"
  date: last-modified
  date-format: "[Last Updated on] DD MMMM, YYYY"
  chapters:
    - index.md
    - 01-intro.md
    - 02-access.md
    - 03-onboarding.md
    - 04-access-and-use.md
    - 05-access-data.md
    - 06-where-to-work.md
    - 07-collaborate.md
    - 08-export.md
    - 09-dos-and-donts.md
    - 10-packages.md
    - 11-querying-guide.md
    - 12-dashboards.md
    - 13-pass_reset_password.md
    - 14-faq.md
  search: 
    location: sidebar
    type: textbox

format:
  html:
    theme: journal
    backgroundcolor: "white"
    highlight-style: arrow
    embed-resources: false
    toc: true
    df-print: paged
    number-sections: false 
    number-depth: 1
    sidebar: 
      background: "#4c2a9d"
      search: true
      style: floating

editor: visual
